Implement http sse source extension
siddhi-io/siddhi-io-http pull request #188
Opened 2021-02-16 19:49 UTC by cazci

## Purpose
>To add http sse source support 

## Goals
> This will completed the above purpose

2021-02-16 20:16 UTC, ramindu90 requested changes

2021-02-16 20:16 UTC, ramindu90 commented on component/src/main/java/io/siddhi/extension/io/http/util/HttpConstants.java
> +    public static final String LISTENER_URL = "listener.url";
@cazci I think this should be changed to 'event.source.url'

2021-02-16 20:16 UTC, ramindu90 commented on component/src/test/resources/testng.xml
>  </suite>
@cazci Please add a new line here

2021-02-16 20:16 UTC, ramindu90 commented on component/src/main/java/io/siddhi/extension/io/http/source/HttpSSESource.java
> +        String contentType = HttpConstants.APPLICATION_JSON;
@cazci shall we make content-type parameterized? since in sse, theres are several types including 'text/event-stream'

2021-02-17 05:51 UTC, ramindu90 approved these changes

2021-02-17 05:51 UTC, sajithshn approved these changes

2021-02-17 05:51 UTC, merged